// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx5sL4rVHj12NVliT1zMUvO2LeIJvSNZk',
    appId: '1:650944579963:ios:5b0b543077d47177ad95de',
    messagingSenderId: '650944579963',
    projectId: 'nurhealth-app',
    storageBucket: 'nurhealth-app.firebasestorage.app',
    iosBundleId: 'com.example.nurhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx5sL4rVHj12NVliT1zMUvO2LeIJvSNZk',
    appId: '1:650944579963:ios:5b0b543077d47177ad95de',
    messagingSenderId: '650944579963',
    projectId: 'nurhealth-app',
    storageBucket: 'nurhealth-app.firebasestorage.app',
    iosBundleId: 'com.example.nurhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhb0VF5fSoXg6gBbsyxGGgo_8uDAtq9E',
    appId: '1:650944579963:web:b96b4c28aea90e12ad95de',
    messagingSenderId: '650944579963',
    projectId: 'nurhealth-app',
    authDomain: 'nurhealth-app.firebaseapp.com',
    storageBucket: 'nurhealth-app.firebasestorage.app',
  );
}
